### ISSUE TITLE
启动器打开报错

### ISSUE THREAD

**Issue by NamazuKashima** [ottercorp/FFXIVQuickLauncher#101]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

正常启动蓝月亮 无法获取大区 一段时间后报错
重装蓝月亮无数次 无法解决
重装系统两次 无法解决

### 平台

Windows

### 相关日志文件

```shell
2024-11-10 13:08:41.316 -05:00 [INF] Starting a session(v6.4.2.0 - 6.4.2-beta6-0-g31dbacf1)
2024-11-10 13:08:41.779 -05:00 [INF] Trying to set up Loc for language code en
2024-11-10 13:08:41.927 -05:00 [INF] Starting update check...
2024-11-10 13:08:44.770 -05:00 [INF] Feature flags: None
2024-11-10 13:08:54.018 -05:00 [INF] MainWindow initialized.
2024-11-10 13:08:54.585 -05:00 [INF] [DUPDATE] Starting... (forceProxy: false)
2024-11-10 13:08:54.796 -05:00 [INF] [DUPDATE] Using release version (10.0.0.16)
2024-11-10 13:08:57.618 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 8.0.3
2024-11-10 13:09:01.270 -05:00 [INF] [DUPDATE] All set for 2024.10.10.0000.0000 with 10.0.0.16(8.0.3, 101)
2024-11-10 13:11:29.888 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMS0xMFQxMzoxMToyOS44ODQzNzE0LTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IEEgVGFzaydzIGV4Y2VwdGlvbihzKSB3ZXJlIG5vdCBvYnNlcnZlZCBlaXRoZXIgYnkgV2FpdGluZyBvbiB0aGUgVGFzayBvciBhY2Nlc3NpbmcgaXRzIEV4Y2VwdGlvbiBwcm9wZXJ0eS4gQXMgYSByZXN1bHQsIHRoZSB1bm9ic2VydmVkIGV4Y2VwdGlvbiB3YXMgcmV0aHJvd24gYnkgdGhlIGZpbmFsaXplciB0aHJlYWQuIC0tLT4gU3lzdGVtLk5ldC5IdHRwLkh0dHBSZXF1ZXN0RXhjZXB0aW9uOiBBbiBlcnJvciBvY2N1cnJlZCB3aGlsZSBzZW5kaW5nIHRoZSByZXF1ZXN0LiAtLS0+IFN5c3RlbS5OZXQuV2ViRXhjZXB0aW9uOiBVbmFibGUgdG8gY29ubmVjdCB0byB0aGUgcmVtb3RlIHNlcnZlciAtLS0+IFN5c3RlbS5OZXQuU29ja2V0cy5Tb2NrZXRFeGNlcHRpb246IEEgY29ubmVjdGlvbiBhdHRlbXB0IGZhaWxlZCBiZWNhdXNlIHRoZSBjb25uZWN0ZWQgcGFydHkgZGlkIG5vdCBwcm9wZXJseSByZXNwb25kIGFmdGVyIGEgcGVyaW9kIG9mIHRpbWUsIG9yIGVzdGFibGlzaGVkIGNvbm5lY3Rpb24gZmFpbGVkIGJlY2F1c2UgY29ubmVjdGVkIGhvc3QgaGFzIGZhaWxlZCB0byByZXNwb25kIDE1Ny4xODUuMTY4LjE0OjQ0M1xyXG4gICBhdCBTeXN0ZW0uTmV0LlNvY2tldHMuU29ja2V0LkludGVybmFsRW5kQ29ubmVjdChJQXN5bmNSZXN1bHQgYXN5bmNSZXN1bHQpXHJcbiAgIGF0IFN5c3RlbS5OZXQuU29ja2V0cy5Tb2NrZXQuRW5kQ29ubmVjdChJQXN5bmNSZXN1bHQgYXN5bmNSZXN1bHQpXHJcbiAgIGF0IFN5c3RlbS5OZXQuU2VydmljZVBvaW50LkNvbm5lY3RTb2NrZXRJbnRlcm5hbChCb29sZWFuIGNvbm5lY3RGYWlsdXJlLCBTb2NrZXQgczQsIFNvY2tldCBzNiwgU29ja2V0JiBzb2NrZXQsIElQQWRkcmVzcyYgYWRkcmVzcywgQ29ubmVjdFNvY2tldFN0YXRlIHN0YXRlLCBJQXN5bmNSZXN1bHQgYXN5bmNSZXN1bHQsIEV4Y2VwdGlvbiYgZXhjZXB0aW9uKVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwV2ViUmVxdWVzdC5FbmRHZXRSZXNwb25zZShJQXN5bmNSZXN1bHQgYXN5bmNSZXN1bHQpXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5IdHRwQ2xpZW50SGFuZGxlci5HZXRSZXNwb25zZUNhbGxiYWNrKElBc3luY1Jlc3VsdCBhcilcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFhJVkxhdW5jaGVyLldpbmRvd3MuTWFpbldpbmRvdy48U2V0dXBTZXJ2ZXJzPmRfXzE2Lk1vdmVOZXh0KCkgaW4gRDpcXGFcXEZGWElWUXVpY2tMYXVuY2hlclxcRkZYSVZRdWlja0xhdW5jaGVyXFxzcmNcXFhJVkxhdW5jaGVyXFxXaW5kb3dzXFxNYWluV2luZG93LnhhbWwuY3M6bGluZSAxMzBcclxuLS0tIEVuZCBvZiBzdGFjayB0cmFjZSBmcm9tIHByZXZpb3VzIGxvY2F0aW9uIHdoZXJlIGV4Y2VwdGlvbiB3YXMgdGhyb3duIC0tLVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZS5FeGNlcHRpb25TZXJ2aWNlcy5FeGNlcHRpb25EaXNwYXRjaEluZm8uVGhyb3coKVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzLlRhc2tBd2FpdGVyLkhhbmRsZU5vblN1Y2Nlc3NBbmREZWJ1Z2dlck5vdGlmaWNhdGlvbihUYXNrIHRhc2spXHJcbiAgIGF0IFhJVkxhdW5jaGVyLldpbmRvd3MuTWFpbldpbmRvdy48PmNfX0Rpc3BsYXlDbGFzczIyXzAuPDxJbml0aWFsaXplPmJfXzA+ZC5Nb3ZlTmV4dCgpIGluIEQ6XFxhXFxGRlhJVlF1aWNrTGF1bmNoZXJcXEZGWElWUXVpY2tMYXVuY2hlclxcc3JjXFxYSVZMYXVuY2hlclxcV2luZG93c1xcTWFpbldpbmRvdy54YW1sLmNzOmxpbmUgNDU3XHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4tLS0+IChJbm5lciBFeGNlcHRpb24gIzApIFN5c3RlbS5OZXQuSHR0cC5IdHRwUmVxdWVzdEV4Y2VwdGlvbjogQW4gZXJyb3Igb2NjdXJyZWQgd2hpbGUgc2VuZGluZyB0aGUgcmVxdWVzdC4gLS0tPiBTeXN0ZW0uTmV0LldlYkV4Y2VwdGlvbjogVW5hYmxlIHRvIGNvbm5lY3QgdG8gdGhlIHJlbW90ZSBzZXJ2ZXIgLS0tPiBTeXN0ZW0uTmV0LlNvY2tldHMuU29ja2V0RXhjZXB0aW9uOiBBIGNvbm5lY3Rpb24gYXR0ZW1wdCBmYWlsZWQgYmVjYXVzZSB0aGUgY29ubmVjdGVkIHBhcnR5IGRpZCBub3QgcHJvcGVybHkgcmVzcG9uZCBhZnRlciBhIHBlcmlvZCBvZiB0aW1lLCBvciBlc3RhYmxpc2hlZCBjb25uZWN0aW9uIGZhaWxlZCBiZWNhdXNlIGNvbm5lY3RlZCBob3N0IGhhcyBmYWlsZWQgdG8gcmVzcG9uZCAxNTcuMTg1LjE2OC4xNDo0NDNcclxuICAgYXQgU3lzdGVtLk5ldC5Tb2NrZXRzLlNvY2tldC5JbnRlcm5hbEVuZENvbm5lY3QoSUFzeW5jUmVzdWx0IGFzeW5jUmVzdWx0KVxyXG4gICBhdCBTeXN0ZW0uTmV0LlNvY2tldHMuU29ja2V0LkVuZENvbm5lY3QoSUFzeW5jUmVzdWx0IGFzeW5jUmVzdWx0KVxyXG4gICBhdCBTeXN0ZW0uTmV0LlNlcnZpY2VQb2ludC5Db25uZWN0U29ja2V0SW50ZXJuYWwoQm9vbGVhbiBjb25uZWN0RmFpbHVyZSwgU29ja2V0IHM0LCBTb2NrZXQgczYsIFNvY2tldCYgc29ja2V0LCBJUEFkZHJlc3MmIGFkZHJlc3MsIENvbm5lY3RTb2NrZXRTdGF0ZSBzdGF0ZSwgSUFzeW5jUmVzdWx0IGFzeW5jUmVzdWx0LCBFeGNlcHRpb24mIGV4Y2VwdGlvbilcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cFdlYlJlcXVlc3QuRW5kR2V0UmVzcG9uc2UoSUFzeW5jUmVzdWx0IGFzeW5jUmVzdWx0KVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENsaWVudEhhbmRsZXIuR2V0UmVzcG9uc2VDYWxsYmFjayhJQXN5bmNSZXN1bHQgYXIpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBYSVZMYXVuY2hlci5XaW5kb3dzLk1haW5XaW5kb3cuPFNldHVwU2VydmVycz5kX18xNi5Nb3ZlTmV4dCgpIGluIEQ6XFxhXFxGRlhJVlF1aWNrTGF1bmNoZXJcXEZGWElWUXVpY2tMYXVuY2hlclxcc3JjXFxYSVZMYXVuY2hlclxcV2luZG93c1xcTWFpbldpbmRvdy54YW1sLmNzOmxpbmUgMTMwXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiB3aGVyZSBleGNlcHRpb24gd2FzIHRocm93biAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWUuRXhjZXB0aW9uU2VydmljZXMuRXhjZXB0aW9uRGlzcGF0Y2hJbmZvLlRocm93KClcclxuICAgYXQgU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcy5UYXNrQXdhaXRlci5IYW5kbGVOb25TdWNjZXNzQW5kRGVidWdnZXJOb3RpZmljYXRpb24oVGFzayB0YXNrKVxyXG4gICBhdCBYSVZMYXVuY2hlci5XaW5kb3dzLk1haW5XaW5kb3cuPD5jX19EaXNwbGF5Q2xhc3MyMl8wLjw8SW5pdGlhbGl6ZT5iX18wPmQuTW92ZU5leHQoKSBpbiBEOlxcYVxcRkZYSVZRdWlja0xhdW5jaGVyXFxGRlhJVlF1aWNrTGF1bmNoZXJcXHNyY1xcWElWTGF1bmNoZXJcXFdpbmRvd3NcXE1haW5XaW5kb3cueGFtbC5jczpsaW5lIDQ1NzwtLS1cclxuIiwiQ29udGV4dCI6IlVuaGFuZGxlZCBleGNlcHRpb24ifQ==
2024-11-10 13:11:29.840 -05:00 [ERR] Unhandled exception
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 157.185.168.14:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at XIVLauncher.Windows.MainWindow.<SetupServers>d__16.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.MainWindow.<>c__DisplayClass22_0.<<Initialize>b__0>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 457
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 157.185.168.14:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at XIVLauncher.Windows.MainWindow.<SetupServers>d__16.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.MainWindow.<>c__DisplayClass22_0.<<Initialize>b__0>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 457<---

2024-11-10 13:19:11.293 -05:00 [INF] ========================================================
2024-11-10 13:19:11.308 -05:00 [INF] Starting a session(v6.4.2.0 - 6.4.2-beta6-0-g31dbacf1)
2024-11-10 13:19:11.755 -05:00 [INF] Trying to set up Loc for language code en
2024-11-10 13:19:11.910 -05:00 [INF] Starting update check...
2024-11-10 13:19:14.348 -05:00 [INF] Feature flags: None
2024-11-10 13:19:15.233 -05:00 [INF] MainWindow initialized.
2024-11-10 13:19:15.675 -05:00 [INF] [DUPDATE] Starting... (forceProxy: false)
2024-11-10 13:19:15.888 -05:00 [INF] [DUPDATE] Using release version (10.0.0.16)
2024-11-10 13:19:18.251 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 8.0.3
2024-11-10 13:19:19.570 -05:00 [INF] [DUPDATE] All set for 2024.10.10.0000.0000 with 10.0.0.16(8.0.3, 101)
2024-11-10 13:20:49.155 -05:00 [INF] ========================================================
2024-11-10 13:20:49.166 -05:00 [INF] Starting a session(v6.4.2.0 - 6.4.2-beta6-0-g31dbacf1)
2024-11-10 13:20:49.295 -05:00 [INF] Trying to set up Loc for language code en
2024-11-10 13:20:49.361 -05:00 [INF] Starting update check...
2024-11-10 13:20:51.025 -05:00 [INF] Feature flags: None
2024-11-10 13:20:51.543 -05:00 [INF] MainWindow initialized.
2024-11-10 13:20:51.939 -05:00 [INF] [DUPDATE] Starting... (forceProxy: false)
2024-11-10 13:20:52.287 -05:00 [INF] [DUPDATE] Using release version (10.0.0.16)
2024-11-10 13:20:52.400 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 8.0.3
2024-11-10 13:20:53.014 -05:00 [INF] [DUPDATE] All set for 2024.10.10.0000.0000 with 10.0.0.16(8.0.3, 101)
```

**Comment by Bluefissure** [comment]
加拿大的运营商的问题
20241110 ff.dorado.sdo.com 在加拿大无法访问。Google，Cloudflare和opendns等等公共dns可以给出IP地址， 157.185.165.36和157.185.168.14。经过 tracert 跟踪后，疑似是盛趣的CDN服务商网宿在加拿大的本地CDN合作伙伴Meteverse的peering network间无法路由 
临时解决方案是在hosts文件中添加Meteverse CDN在美国的ip地址157.185.176.130,  157.185.176.144 或者 157.185.179.22
  `157.185.176.130 ff.dorado.sdo.com # ff14 temp`

目前似乎已恢复
