### ISSUE TITLE
特定网络环境下无法正常启动卫月

### ISSUE THREAD

**Issue by broadpath693** [ottercorp/FFXIVQuickLauncher#103]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

打开启动器广告无法加载，不默认输入账户，且打开账户管理就会一键未响应，启用禁用自动注入和卫月均无法恢复正常，仅在校园网状态下有此bug，其他环境均正常，更改dns服务器也无法正确启动
![1734519194076](https://github.com/user-attachments/assets/a6f0df32-1502-4978-b18b-7307e1a71ffc)

### 平台

Windows

### 相关日志文件

```shell
XIVLauncher 发生错误。请查阅常见问题以找到解决方案。 如果问题仍然存在，请点击下面的按钮，在GitHub 上报告，描述问题并附上方框内的文本。

Error during early initialization. Please report this error.

System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at XIVLauncher.Windows.MainWindow.SwitchAccount(XivAccount account, Boolean saveAsCurrent)
   at XIVLauncher.Windows.MainWindow.OnAccountSwitchedEventHandler(Object sender, XivAccount e)
   at XIVLauncher.Windows.AccountSwitcher.AccountListView_OnMouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at XIVLauncher.App.Main()
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at XIVLauncher.Windows.MainWindow.SwitchAccount(XivAccount account, Boolean saveAsCurrent)
   at XIVLauncher.Windows.MainWindow.OnAccountSwitchedEventHandler(Object sender, XivAccount e)
   at XIVLauncher.Windows.AccountSwitcher.AccountListView_OnMouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at XIVLauncher.App.Main()

Version: 6.4.3.0
Git Hash: 6.4.3-4-0-g8e2727a5
Context: Unhandled
OS: Microsoft Windows NT 10.0.19045.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: E:\ff14\最终幻想XIV
```

**Comment by broadpath693** [comment]
删除已保存的账号后发现无法正常获取服务器大区，不管是国内dns还是国外dns都无法正常使用

**Comment by Loskh** [comment]
账号管理已重构，另尝试修复获取大区
