### ISSUE TITLE
5003错误

### ISSUE THREAD

**Issue by liricliu** [ottercorp/FFXIVQuickLauncher#24]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

按照正常步骤打开，可以打开游戏，但是会发生账号认证错误（5003）

### 平台

Windows

**Comment by Loskh** [comment]
请附上log

**Comment by sorry77** [comment]
同样的问题，手机上提示成功了，看上去运行参数的token比前面的短？

`
2022-07-18 10:12:54.957 +08:00 [INF] codeKeyLogin.json:ErrorType=0:ReturnCode=-10515805:FailReason:二维码未通过验证，请重试

2022-07-18 10:12:56.052 +08:00 [INF] codeKeyLogin.json:ErrorType=0:ReturnCode=0:FailReason:
2022-07-18 10:12:56.122 +08:00 [INF] getPromotionInfo.json:ErrorType=0:ReturnCode=0:FailReason:
2022-07-18 10:12:56.183 +08:00 [INF] ssoLogin.json:ErrorType=0:ReturnCode=0:FailReason:
2022-07-18 10:12:56.280 +08:00 [ERR] Could not find ucrtbase_clr0400
2022-07-18 10:12:56.280 +08:00 [ERR] Missing DLL files required by Dalamud.
2022-07-18 10:12:56.280 +08:00 [ERR] No Dalamud Redists found
XIVLauncher.Common.PlatformAbstractions.IDalamudCompatibilityCheck+NoRedistsException: Exception of type 'XIVLauncher.Common.PlatformAbstractions.IDalamudCompatibilityCheck+NoRedistsException' was thrown.
   at XIVLauncher.Common.Windows.WindowsDalamudCompatibilityCheck.EnsureCompatibility() in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudCompatibilityCheck.cs:line 15
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1037
2022-07-18 10:12:56.292 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNy0xOFQxMDoxMjo1Ni4yODk1NTMrMDg6MDAiLCJJbmZvIjoiWElWTGF1bmNoZXIuQ29tbW9uLlBsYXRmb3JtQWJzdHJhY3Rpb25zLklEYWxhbXVkQ29tcGF0aWJpbGl0eUNoZWNrK05vUmVkaXN0c0V4Y2VwdGlvbjogRXhjZXB0aW9uIG9mIHR5cGUgJ1hJVkxhdW5jaGVyLkNvbW1vbi5QbGF0Zm9ybUFic3RyYWN0aW9ucy5JRGFsYW11ZENvbXBhdGliaWxpdHlDaGVjaytOb1JlZGlzdHNFeGNlcHRpb24nIHdhcyB0aHJvd24uXHJcbiAgIGF0IFhJVkxhdW5jaGVyLkNvbW1vbi5XaW5kb3dzLldpbmRvd3NEYWxhbXVkQ29tcGF0aWJpbGl0eUNoZWNrLkVuc3VyZUNvbXBhdGliaWxpdHkoKSBpbiBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb24uV2luZG93c1xcV2luZG93c0RhbGFtdWRDb21wYXRpYmlsaXR5Q2hlY2suY3M6bGluZSAxNVxyXG4gICBhdCBYSVZMYXVuY2hlci5XaW5kb3dzLlZpZXdNb2RlbC5NYWluV2luZG93Vmlld01vZGVsLjxTdGFydEdhbWVBbmRBZGRvbj5kX18zMC5Nb3ZlTmV4dCgpIGluIEQ6XFxhXFxGRlhJVlF1aWNrTGF1bmNoZXJcXEZGWElWUXVpY2tMYXVuY2hlclxcc3JjXFxYSVZMYXVuY2hlclxcV2luZG93c1xcVmlld01vZGVsXFxNYWluV2luZG93Vmlld01vZGVsLmNzOmxpbmUgMTAzNyIsIkNvbnRleHQiOiJObyBEYWxhbXVkIFJlZGlzdHMgZm91bmQifQ==
2022-07-18 10:12:58.263 +08:00 [INF] XivGame::LaunchGame(args:)
2022-07-18 10:13:00.395 +08:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMi0wNy0xOFQxMDoxMzowMC4zOTIxMTgrMDg6MDAiLCJJc0R4MTEiOnRydWUsIklzQXV0b0xvZ2luIjpmYWxzZSwiSXNVaWRDYWNoZSI6ZmFsc2UsIkRhbGFtdWRFbmFibGVkIjpmYWxzZSwiRGFsYW11ZExvYWRNZXRob2QiOjEsIkRhbGFtdWRJbmplY3Rpb25EZWxheSI6MC4wLCJTdGVhbUludGVncmF0aW9uIjpmYWxzZSwiRW5jcnlwdEFyZ3VtZW50cyI6ZmFsc2UsIkxhdW5jaGVyVmVyc2lvbiI6IjYuMi4zOC4wIiwiTGF1bmNoZXJIYXNoIjoiNi4yLjM4LWJldGEzLTAtZzFjYmNhMmEiLCJPZmZpY2lhbCI6ZmFsc2UsIkRwaUF3YXJlbmVzcyI6MSwiUGxhdGZvcm0iOjEsIk9ic2VydmVkR2FtZVZlcnNpb24iOiIyMDIyLjA0LjE1LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgxVmVyc2lvbiI6IjIwMjIuMDIuMTcuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDJWZXJzaW9uIjoiMjAyMi4wMi4xNy4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4M1ZlcnNpb24iOiIyMDIyLjAzLjIzLjAwMDAuMDAwMCIsIk9ic2VydmVkRXg0VmVyc2lvbiI6IjIwMjIuMDQuMDguMDAwMC4wMDAwIiwiQmNrTWF0Y2giOmZhbHNlLCJJbmRleEludGVncml0eSI6NX0=
2022-07-18 10:13:36.856 +08:00 [INF] Stopping addons...
`

**Comment by liricliu** [comment]
问题找到了，是Wine下不支持中文路径
