### ISSUE TITLE
wine环境下启用Dalamud后无法登陆

### ISSUE THREAD

**Issue by hy101** [ottercorp/FFXIVQuickLauncher#25]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

XIVLauncher可以正常启动游戏，但是启用Dalamud功能后无法启动

### 平台

Linux (Wine/Proton)

### Wine/Proton 运行版本

lutris-GE-Proton7-20-x86_64

### 相关日志文件

```shell
System.ArgumentException: Item has already been added. Key in dictionary: 'NO_PROXY'  Key being added: 'no_proxy'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 52
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 78
   at XIVLauncher.Common.Game.Launcher.LaunchGameSdo(IGameRunner runner, String sessionId, String sndaId, String areaId, String lobbyHost, String gmHost, String dbHost, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:line 508
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 661

Version: 6.2.38.0
Git Hash: 6.2.38-beta3-0-g1cbca2a
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: SimplifiedChinese
Game path: C:\Program Files (x86)\SNDA\FFXIV
```

**Comment by Bluefissure** [comment]
Same issue [here](https://github.com/goatcorp/FFXIVQuickLauncher/issues/1018)

**Comment by Bluefissure** [comment]
我认为这是因为 Unix 环境变量是区分大小写的，但在 Windows 上它们不是，wine 使 `psi.EnvironmentVariables`  [代码](https://github.com/goatcorp/FFXIVQuickLauncher/blob/0903938/src/XIVLauncher.Common.Windows/WindowsDalamudRunner.cs#L50) 像在 Unix 中一样使用它并生成具有不同大小写的相同环境变量，但是在将变量移植到 wine 时出现了问题。
要解决此问题，我们可以尝试 [corefx](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.cs#L90) 中的类似方法。
相关讨论：https://github.com/dotnet/runtime/issues/19142
