### ISSUE TITLE
Mac环境下XIVLauncherCN无法更新补丁

### ISSUE THREAD

**Issue by dahsjun** [ottercorp/FFXIVQuickLauncher#26]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

https://zhuanlan.zhihu.com/p/539627025
按照这一篇文章做的步骤
第一次下载了国际服版本的ff14，但在打开LauncherCN的时候提示“服务器发送了无效的响应”
删除了国际服版本之后用官网下载器下载了国服ff14，按安装器默认装在了C盘，在更新补丁的时候显示报错
删除了C盘里的ff14之后又安装在了Z盘，但是报错没有改变
另外在检测游戏完整性的界面里有显示“XIVLauncher不支持国服/韩服的游戏版本，请确认是国际服版本”，但我很确定我打开的是XIVLauncherCN
没有启用Dalamud

### 平台

Mac OS X

### Wine/Proton 运行版本

不会看wine的版本...不好意思

### 相关日志文件

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Game.Patch.PatchManager..ctor(AcquisitionMethod acquisitionMethod, Int64 speedLimitBytes, Repository repo, IEnumerable`1 patches, DirectoryInfo gamePath, DirectoryInfo patchStore, PatchInstaller installer, Launcher launcher, String sid) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 94
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__35.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 625
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 277
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass20_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 154
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Game.Patch.PatchManager..ctor(AcquisitionMethod acquisitionMethod, Int64 speedLimitBytes, Repository repo, IEnumerable`1 patches, DirectoryInfo gamePath, DirectoryInfo patchStore, PatchInstaller installer, Launcher launcher, String sid) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 94
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__35.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 625
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 277<---


Version: 6.2.38.0
Git Hash: 6.2.38-beta3-0-g1cbca2a
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: SimplifiedChinese
Game path: Z:\Users\yuugao\Documents\New Folder\FFXIV

**Comment by Bluefissure** [comment]
需要给 `launcherConfigV3.json` 添加 Gamepath:
```
{
  "AcceptLanguage": "ja",
  "LauncherLanguage": "SimplifiedChinese",
  "AddonList": "[]",
  "PatchAcquisitionMethod": "NetDownloader",
  "InGameAddonLoadMethod": "DllInject",
  "AskBeforePatchInstall": "true",
  "DpiAwareness": "Unaware",
  "TreatNonZeroExitCodeAsFailure": "false",
  "ExitLauncherAfterGameExit": "true",
  "IsFt": "false",
  "UniqueIdCacheEnabled": "false",
  "EncryptArguments": "false",
  "GamePath": "Z:\\Users\\xxx\\ffxivcn",
  "VersionUpgradeLevel": "1",
  "SelectedServer": "0",
  "CurrentAccountId": "1234567890-False-False",
  "AutologinEnabled": "false",
  "FastLogin": "false",
  "IsDx11": "true",
  "Language": "English",
  "KeepPatches": "false",
  "InGameAddonEnabled": "false",
  "DalamudInjectionDelayMs": "0",
  "OtpServerEnabled": "false",
  "AdditionalLaunchArgs": "",
  "SpeedLimitBytes": "0"
}
```

**Comment by gtbl2012** [comment]
找到了一个初步解决方案：
手动在 launcher设置->更新->指定一个更新目录 即可绕过这个报错

**Comment by Bluefissure** [comment]
建议使用 xlcore 安装更新，wine里面的权限可能有问题

**Comment by Loskh** [comment]
XL已修复 bdd307f61dc0bb9ac8b5da752d0a8a47d0d857a1
Core正常
