### ISSUE TITLE
XIVLauncher与插件可正常启动工作，但是退出游戏时报appcrash

### ISSUE THREAD

**Issue by YihanMie** [ottercorp/FFXIVQuickLauncher#34]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

在6.1更新后我已删除Dalamud中的测试版与第三方库插件，并且在周二到今天正常使用了XIVLauncher与主库中已更新的插件进行游戏。但在今天退出游戏（大退）时，XIVLauncher弹出了一个报错，然而下一次通过它启动游戏时，启动器与插件依旧正常工作。

报错内容为：
[dalamud_appcrash_20220812_045630_120_4116.log](https://github.com/ottercorp/FFXIVQuickLauncher/files/9312132/dalamud_appcrash_20220812_045630_120_4116.log)

### 平台

Windows

### 相关日志文件

```shell
Unhandled native exception occurred at ffxiv_dx11.exe+51120B
Code: C0000005
Dump at: C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\..\..\..\dalamud_appcrash_20220812_045630_120_4116.dmp
Time: 2022-08-12 04:56:30.6546412 GMT+8

   at System.Environment.get_StackTrace()
   at Dalamud.EntryPoint.VehCallback() in D:\a\Dalamud\Dalamud\Dalamud\EntryPoint.cs:line 70

Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF71FEA120B
Parameters: 0, FFFFFFFFFFFFFFFF
Call Stack
{
  [0]	ffxiv_dx11.exe+51120B
  [1]	ffxiv_dx11.exe+51120B
  [2]	ffxiv_dx11.exe+50ABCF
  [3]	264BAFD76B0
  [4]	ffxiv_dx11.exe+513606
  [5]	ffxiv_dx11.exe+539C84
  [6]	ffxiv_dx11.exe+5F5B5C
  [7]	ffxiv_dx11.exe+94989
  [8]	ffxiv_dx11.exe+17FC3D
  [9]	ffxiv_dx11.exe+17FE73
  [10]	ffxiv_dx11.exe+92D4F
  [11]	ffxiv_dx11.exe+56365
  [12]	ffxiv_dx11.exe+59EA6
  [13]	ffxiv_dx11.exe+14A498F
  [14]	1000
}

Registers
{
  RAX:	D
  RBX:	264BAFD76B0 [ffxiv_dx11.exe+19293A8	(GFSDK_SSAO_CreateContext_D3D11+0x47E1A8)]
  RCX:	FDB7F7E9A8 [FDB7F7EA18]
  RDX:	264BAFD76B8 [694C79747261505F]
  R8:	0
  R9:	1
  R10:	42
  R11:	FDB7F7EAE0 [ffxiv_dx11.exe+50ABCF]
  R12:	FDB7F7EE00 [264BAFD76B0]
  R13:	0
  R14:	1
  R15:	0
  RSI:	26540CCF250 [40A0000000000000]
  RDI:	D
  RBP:	FDB7F7EA58 [FDB7F7EA78]
  RSP:	FDB7F7E958
  RIP:	ffxiv_dx11.exe+51120B [C03345C873290F41]
}

Stack
{
  [RSP+0]	0
  [RSP+8]	20
  [RSP+10]	2647D81ED10 [2651B437240]
  [RSP+18]	26540A0CC10 [E68687E5BEB2E78B]
  [RSP+20]	26484F01428 [300770090]
  [RSP+28]	ffxiv_dx11.exe+4D8E9F [60C8B4810438B48]
  [RSP+30]	264BAFD76B8 [694C79747261505F]
  [RSP+38]	0
  [RSP+40]	0
  [RSP+48]	20
  [RSP+50]	FDB7F7EA18 [26400000000]
  [RSP+58]	ffxiv_dx11.exe+538574 [750F3040F64124EB]
  [RSP+60]	26484EFF8E0 [ffxiv_dx11.exe+17DAA30	(GFSDK_SSAO_CreateContext_D3D11+0x32F830)]
  [RSP+68]	1
  [RSP+70]	0
  [RSP+78]	3
}

Modules
{
  00400000	C:\Windows\SYSTEM32\XInput1_3.dll
  10000000	C:\Program Files (x86)\SogouInput\12.1.0.6042\Resource.dll
  510A0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\FASMX64.dll
  180000000	C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
  26478A90000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\PInvoke.User32.dll
  26478AB0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\PInvoke.Windows.Core.dll
  26478B00000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\MonoMod.Utils.dll
  26478B40000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Mono.Cecil.dll
  26478BB0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Serilog.dll
  26478BE0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Serilog.Sinks.Async.dll
  26478BF0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Serilog.Sinks.Console.dll
  26478C10000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Dalamud.dll
  26478D30000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Serilog.Sinks.File.dll
  26478D40000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\PInvoke.Kernel32.dll
  26478D60000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Lumina.dll
  2647B170000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Newtonsoft.Json.dll
  2647B220000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\ImGui.NET.dll
  2647B2B0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\FFXIVClientStructs.dll
  2647B340000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\ImGuiScene.dll
  2647BB40000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\MonoMod.RuntimeDetour.dll
  2647BB90000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\CheapLoc.dll
  2647F540000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Lumina.Excel.dll
  2647F750000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Iced.dll
  2647F930000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Reloaded.Hooks.dll
  2647F9C0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Reloaded.Hooks.Definitions.dll
  2647F9E0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Reloaded.Memory.Buffers.dll
  2647F9F0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Reloaded.Memory.dll
  2647FA10000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\Reloaded.Assembler.dll
  2647FC90000	C:\Dalamud\XIVLauncherCN\Roaming\runtime\shared\Microsoft.NETCore.App\5.0.17\mscorlib.dll
  26489BC0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\SharpDX.DXGI.dll
  26489BF0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\SharpDX.dll
  26489C40000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\SharpDX.Direct3D11.dll
  26489CB0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\SharpDX.Mathematics.dll
  2648BDF0000	C:\Dalamud\XIVLauncherCN\Roaming\addon\Hooks\6.4.0.46\StbiSharp.dll
  7FF71F990000	C:\Program Files (x86)\
```

**Comment by Bluefissure** [comment]
卫月设置中的测试版中将第一个插件卸载延迟调大
