### ISSUE TITLE
发生了未知错误

### ISSUE THREAD

**Issue by chunsiyang** [ottercorp/FFXIVQuickLauncher#39]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

点击开始游戏，报错，无法启动游戏

### 平台

Windows

### 相关日志文件

```shell
XIVLauncher.Common.Dalamud.DalamudRunnerException: An internal Dalamud error has occured
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 62
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 78
   at XIVLauncher.Common.Game.Launcher.LaunchGameSdo(IGameRunner runner, String sessionId, String sndaId, String areaId, String lobbyHost, String gmHost, String dbHost, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:line 595
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 665

Version: 6.2.38.0
Git Hash: 6.2.38-beta7-0-g49dda9b
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: D:\entertainment\FF14\最终幻想XIV
```

**Comment by Bluefissure** [comment]
请禁用Dalamud或将其目录加入杀毒软件白名单中
