### ISSUE TITLE
无法打开游戏

### ISSUE THREAD

**Issue by cokoyang** [ottercorp/FFXIVQuickLauncher#87]
### 更新免责声明

- [X] 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。

### 您做了什么？

登录不了

### 平台

Windows

### 相关日志文件

```shell
System.Exception: 未能复制C:\Users\cocoy\Desktop\ff14 stuff\XIVLauncherCN\app-6.3.12-beta2\Resources\sdologinentry64.dll至C:\Program Files (x86)\SNDA\FFXIV\sdo\sdologin\sdologinentry64.dll
请检查程序是否有C:\Program Files (x86)\SNDA\FFXIV\sdo\sdologin\sdologinentry64.dll的写入权限,或者C:\Program Files (x86)\SNDA\FFXIV目录下的游戏正在运行。
Access to the path 'C:\Program Files (x86)\SNDA\FFXIV\sdo\sdologin\sdologinentry64.sdo.dll' is denied.
   at XIVLauncher.Common.Game.Launcher.EnsureLoginEntry(DirectoryInfo gamePath) in C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:line 776
   at XIVLauncher.Common.Game.Launcher.LaunchGameSdo(IGameRunner runner, String sessionId, String sndaId, String areaId, String lobbyHost, String gmHost, String dbHost, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\SdoLauncher.cs:line 688
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__26.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 741

Version: 6.3.12.0
Git Hash: 6.3.12-beta2-0-g5a205c0f
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: ChineseSimplified
LauncherLanguage: SimplifiedChinese
Game path: C:\Program Files (x86)\SNDA\FFXIV
```

**Comment by Loskh** [comment]
`请检查程序是否有C:\Program Files (x86)\SNDA\FFXIV\sdo\sdologin\sdologinentry64.dll的写入权限,或者C:\Program Files (x86)\SNDA\FFXIV目录下的游戏正在运行。`
把正在运行的游戏关掉
